server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB


# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 51200  # 文件上传大小限制为500KB
      max-request-size: 51200 # 文件请求上传大小为500KB

# mybatis配置
mybatis:
  type-aliases-package: com.demo.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers: com.demo.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html

